<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RootNamespace>Photone.Ipc</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Photone.Ipc.Tests" />
    <InternalsVisibleTo Include="Photone.Ipc.TestChild" />
    <InternalsVisibleTo Include="Photone.Ipc.Benchmarks" />
  </ItemGroup>
</Project>
