using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.ComTypes;
using Microsoft.Win32.SafeHandles;
using Windows.Wdk.Foundation;
using Windows.Wdk.System.SystemInformation;
using Windows.Win32.Foundation;
using Windows.Win32.Security;
using Windows.Win32.System.Memory;
using Windows.Win32.System.SystemInformation;
using Windows.Win32.System.Threading;
using Windows.Win32.System.WindowsProgramming;
using Wdk = Windows.Wdk.PInvoke;
using Win32 = Windows.Win32.PInvoke;

namespace Photone.Ipc.Internal;

/// <summary>
/// The library's whole Win32 surface. The declarations and the flag values are generated by CsWin32 from the official Win32 metadata
/// (<c>NativeMethods.txt</c> and <c>NativeMethods.json</c> in the project root); what lives here is the thin layer the rest of the library calls:
/// raw handles on the signal path (no <see cref="SafeHandle"/> AddRef/Release per call), <see cref="SafeHandle"/>s where a handle is owned,
/// plain <see cref="uint"/> wait results (the library does <c>WAIT_OBJECT_0 + index</c> arithmetic on them), the flags under the names the design
/// documents use, and the error helpers. Every wrapper is a cast away from the generated import, so the code the JIT sees is the import itself.
/// <para>
/// The metadata puts <c>VirtualAlloc2</c> and <c>MapViewOfFile3</c> in the <c>api-ms-win-core-memory-l1-1-6</c> API set rather than in
/// <c>kernelbase.dll</c>; the set exists from Windows 10 1803, which <see cref="EnsurePlatform"/> requires anyway (DEVIATIONS §6).
/// </para>
/// </summary>
internal static unsafe class Kernel
{
    /// <summary>Expected allocation granularity; every view and the data region are multiples of it.</summary>
    public const uint ExpectedAllocationGranularity = 65536;

    // ------------------------------------------------------------------ memory: placeholders, views, commit

    /// <summary>Reserves a placeholder, or splits one (DESIGN §4.2).</summary>
    public static void* VirtualAlloc2(nint process, void* baseAddress, nuint size, VIRTUAL_ALLOCATION_TYPE allocationType, PAGE_PROTECTION_FLAGS pageProtection, MEM_EXTENDED_PARAMETER* extendedParameters, uint parameterCount)
        => Win32.VirtualAlloc2((HANDLE)process, baseAddress, size, allocationType, (uint)pageProtection, extendedParameters, parameterCount);

    /// <summary>Maps a view of <paramref name="fileMapping"/>, replacing a placeholder when <c>MEM_REPLACE_PLACEHOLDER</c> is given.</summary>
    public static void* MapViewOfFile3(SafeHandle fileMapping, nint process, void* baseAddress, ulong offset, nuint viewSize, VIRTUAL_ALLOCATION_TYPE allocationType, PAGE_PROTECTION_FLAGS pageProtection, MEM_EXTENDED_PARAMETER* extendedParameters, uint parameterCount)
    {
        ArgumentNullException.ThrowIfNull(fileMapping);
        bool added = false;
        try
        {
            fileMapping.DangerousAddRef(ref added);                  // the section must not close under the call
            return Win32.MapViewOfFile3((HANDLE)fileMapping.DangerousGetHandle(), (HANDLE)process, baseAddress, offset, viewSize, allocationType, (uint)pageProtection, extendedParameters, parameterCount).Value;
        }
        finally
        {
            if (added)
            {
                fileMapping.DangerousRelease();                      // managed only: the last P/Invoke error survives it
            }
        }
    }

    public static bool VirtualFree(void* address, nuint size, VIRTUAL_FREE_TYPE freeType) => Win32.VirtualFree(address, size, freeType);

    /// <summary>Only to commit pages of a view of a <c>SEC_RESERVE</c> section (DESIGN §16.2): the commit belongs to the section, every view sees it.</summary>
    public static void* VirtualAlloc(void* address, nuint size, VIRTUAL_ALLOCATION_TYPE allocationType, PAGE_PROTECTION_FLAGS protect) => Win32.VirtualAlloc(address, size, allocationType, protect);

    public static bool UnmapViewOfFile(void* baseAddress) => Win32.UnmapViewOfFile((MEMORY_MAPPED_VIEW_ADDRESS)baseAddress);

    /// <summary>Create-or-open: on an existing name the call succeeds and the last error is <see cref="WIN32_ERROR.ERROR_ALREADY_EXISTS"/>.</summary>
    public static SafeSectionHandle CreateFileMapping(nint file, SECURITY_ATTRIBUTES* securityAttributes, PAGE_PROTECTION_FLAGS protect, uint maxSizeHigh, uint maxSizeLow, string? name)
    {
        fixed (char* n = name)
        {
            return new SafeSectionHandle(Win32.CreateFileMapping((HANDLE)file, securityAttributes, protect, maxSizeHigh, maxSizeLow, n), ownsHandle: true);
        }
    }

    public static SafeSectionHandle OpenFileMapping(FILE_MAP desiredAccess, bool inheritHandle, string name)
    {
        fixed (char* n = name)
        {
            return new SafeSectionHandle(Win32.OpenFileMapping((uint)desiredAccess, inheritHandle, n), ownsHandle: true);
        }
    }

    // ------------------------------------------------------------------ handles, processes, time

    public static bool CloseHandle(nint handle) => Win32.CloseHandle((HANDLE)handle);

    public static bool DuplicateHandle(nint sourceProcess, nint sourceHandle, nint targetProcess, out nint targetHandle, uint desiredAccess, bool inheritHandle, DUPLICATE_HANDLE_OPTIONS options)
    {
        BOOL ok = Win32.DuplicateHandle((HANDLE)sourceProcess, (HANDLE)sourceHandle, (HANDLE)targetProcess, out HANDLE dup, desiredAccess, inheritHandle, options);
        targetHandle = dup;
        return ok;
    }

    /// <summary>Pseudo handle (-1); never close it.</summary>
    public static nint GetCurrentProcess() => Win32.GetCurrentProcess();

    /// <summary>The four process times as FILETIME ticks; only the creation time identifies a process (DESIGN §5.7).</summary>
    public static bool GetProcessTimes(nint process, out long creation, out long exit, out long kernel, out long user)
    {
        BOOL ok = Win32.GetProcessTimes((HANDLE)process, out FILETIME c, out FILETIME e, out FILETIME k, out FILETIME u);
        creation = Ticks(c);
        exit = Ticks(e);
        kernel = Ticks(k);
        user = Ticks(u);
        return ok;

        static long Ticks(in FILETIME t) => ((long)(uint)t.dwHighDateTime << 32) | (uint)t.dwLowDateTime;
    }

    public static SafeProcessHandle OpenProcess(PROCESS_ACCESS_RIGHTS desiredAccess, bool inheritHandle, uint processId)
        => new(Win32.OpenProcess(desiredAccess, inheritHandle, processId), ownsHandle: true);

    public static ulong GetTickCount64() => Win32.GetTickCount64();

    // ------------------------------------------------------------------ signaling (raw handles: no AddRef/Release per call)

    /// <summary>Create-or-open: on an existing name the call succeeds and the last error is <see cref="WIN32_ERROR.ERROR_ALREADY_EXISTS"/>.</summary>
    public static SafeWaitHandle CreateEvent(SECURITY_ATTRIBUTES* securityAttributes, bool manualReset, bool initialState, string? name)
    {
        fixed (char* n = name)
        {
            return new SafeWaitHandle(Win32.CreateEvent(securityAttributes, manualReset, initialState, n), ownsHandle: true);
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool SetEvent(nint handle) => Win32.SetEvent((HANDLE)handle);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool ResetEvent(nint handle) => Win32.ResetEvent((HANDLE)handle);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint WaitForSingleObject(nint handle, uint milliseconds) => (uint)Win32.WaitForSingleObject((HANDLE)handle, milliseconds);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint WaitForMultipleObjects(uint count, nint* handles, bool waitAll, uint milliseconds)
        => (uint)Win32.WaitForMultipleObjects(count, (HANDLE*)handles, waitAll, milliseconds);      // HANDLE wraps one pointer: the array needs no copy

    // ------------------------------------------------------------------ ntdll (slow paths only)

    /// <summary>A process snapshot with creation times, which needs no process handle at all (liveness slow path, DESIGN §5.7).</summary>
    public static int NtQuerySystemInformation(SYSTEM_INFORMATION_CLASS systemInformationClass, void* systemInformation, uint systemInformationLength, out uint returnLength)
    {
        returnLength = 0;
        return Wdk.NtQuerySystemInformation(systemInformationClass, systemInformation, systemInformationLength, ref returnLength);
    }

    /// <summary>The system-wide number of open handles to an object (pool slow path, DESIGN §15.3).</summary>
    public static int NtQueryObject(nint handle, OBJECT_INFORMATION_CLASS objectInformationClass, void* objectInformation, uint objectInformationLength, out uint returnLength)
    {
        uint length;
        int status = Wdk.NtQueryObject((HANDLE)handle, objectInformationClass, objectInformation, objectInformationLength, &length);
        returnLength = length;
        return status;
    }

    // ---- helpers (never on a hot path) ----

    private static uint s_allocationGranularity;
    private static uint s_pageSize;

    /// <summary>Allocation granularity reported by <c>GetSystemInfo</c>; throws if it is not 64 KiB (the layout depends on it).</summary>
    public static uint AllocationGranularity
    {
        get
        {
            if (s_allocationGranularity == 0)
            {
                QuerySystemInfo();
            }

            return s_allocationGranularity;
        }
    }

    /// <summary>Page size reported by <c>GetSystemInfo</c>.</summary>
    public static uint PageSize
    {
        get
        {
            if (s_pageSize == 0)
            {
                QuerySystemInfo();
            }

            return s_pageSize;
        }
    }

    private static void QuerySystemInfo()
    {
        Win32.GetSystemInfo(out SYSTEM_INFO si);
        if (si.dwAllocationGranularity != ExpectedAllocationGranularity)
        {
            throw new PhotoneIpcException($"Unsupported allocation granularity {si.dwAllocationGranularity}; photone-ipc requires 65536.");
        }

        if (si.dwPageSize == 0 || (si.dwPageSize & (si.dwPageSize - 1)) != 0)
        {
            throw new PhotoneIpcException($"Unsupported page size {si.dwPageSize}.");
        }

        s_pageSize = si.dwPageSize;
        s_allocationGranularity = si.dwAllocationGranularity;
    }

    /// <summary>Throws <see cref="PlatformNotSupportedException"/> unless running as a 64-bit process on Windows 10 1803 (build 17134) or later.</summary>
    public static void EnsurePlatform()
    {
        if (!OperatingSystem.IsWindowsVersionAtLeast(10, 0, 17134))
        {
            throw new PlatformNotSupportedException("photone-ipc requires Windows 10 version 1803 (build 17134) or later (VirtualAlloc2 / MapViewOfFile3).");
        }

        if (!Environment.Is64BitProcess)
        {
            throw new PlatformNotSupportedException("photone-ipc requires a 64-bit process.");
        }
    }

    /// <summary>
    /// Number of handles open to the object behind <paramref name="handle"/> in all processes (<c>NtQueryObject(ObjectBasicInformation)</c>;
    /// a killed process's handles are gone once it has exited). <see langword="false"/> when the query fails.
    /// </summary>
    public static bool TryQueryHandleCount(SafeHandle handle, out uint handleCount)
    {
        handleCount = 0;
        bool added = false;
        try
        {
            handle.DangerousAddRef(ref added);
            PUBLIC_OBJECT_BASIC_INFORMATION info;
            int status = NtQueryObject(handle.DangerousGetHandle(), OBJECT_INFORMATION_CLASS.ObjectBasicInformation, &info, (uint)sizeof(PUBLIC_OBJECT_BASIC_INFORMATION), out _);
            if (status < 0)
            {
                return false;
            }

            handleCount = info.HandleCount;
            return true;
        }
        catch (ObjectDisposedException)
        {
            return false;
        }
        finally
        {
            if (added)
            {
                handle.DangerousRelease();
            }
        }
    }

    /// <summary>Returns the last P/Invoke error (must be called immediately after a call that sets it).</summary>
    public static int LastError() => Marshal.GetLastPInvokeError();

    /// <summary>Builds a <see cref="PhotoneIpcException"/> describing a failed Win32 call.</summary>
    public static PhotoneIpcException Fail(string api, int error, string? detail = null)
    {
        string message = detail is null
            ? $"{api} failed with Win32 error {error}: {Marshal.GetPInvokeErrorMessage(error).TrimEnd()}"
            : $"{api} failed with Win32 error {error}: {Marshal.GetPInvokeErrorMessage(error).TrimEnd()} ({detail})";
        return new PhotoneIpcException(message, error);
    }
}
