using System.Runtime.InteropServices;
using Windows.Win32;
using Windows.Win32.System.Memory;

// CS0436: this project generates its own CsWin32 types while the library's (internal, visible through InternalsVisibleTo) carry the same names;
//         the compiler prefers the ones from this project's source, which is what these helpers want.
#pragma warning disable CS0436

namespace Photone.Ipc.Tests;

/// <summary>
/// Test-only native calls, generated by CsWin32 (see NativeMethods.txt): what the tests need to look at the placeholders and views the library made,
/// from the outside. The library itself never calls these.
/// </summary>
internal static unsafe class TestKernel
{
    public const uint MEM_COMMIT = (uint)VIRTUAL_ALLOCATION_TYPE.MEM_COMMIT;
    public const uint MEM_RESERVE = (uint)VIRTUAL_ALLOCATION_TYPE.MEM_RESERVE;
    public const uint MEM_FREE = (uint)VIRTUAL_ALLOCATION_TYPE.MEM_FREE;
    public const uint MEM_PRIVATE = (uint)PAGE_TYPE.MEM_PRIVATE;
    public const uint MEM_MAPPED = (uint)PAGE_TYPE.MEM_MAPPED;
    public const uint MEM_RELEASE = (uint)VIRTUAL_FREE_TYPE.MEM_RELEASE;
    public const uint PAGE_NOACCESS = (uint)PAGE_PROTECTION_FLAGS.PAGE_NOACCESS;
    public const uint PAGE_READWRITE = (uint)PAGE_PROTECTION_FLAGS.PAGE_READWRITE;

    public static void* VirtualAlloc(void* address, nuint size, uint allocationType, uint protect)
        => PInvoke.VirtualAlloc(address, size, (VIRTUAL_ALLOCATION_TYPE)allocationType, (PAGE_PROTECTION_FLAGS)protect);

    public static bool VirtualFree(void* address, nuint size, uint freeType) => PInvoke.VirtualFree(address, size, (VIRTUAL_FREE_TYPE)freeType);

    /// <summary>Returns the <c>State</c> of the region containing <paramref name="address"/> (<c>MEM_FREE</c> / <c>MEM_RESERVE</c> / <c>MEM_COMMIT</c>).</summary>
    public static uint QueryState(ulong address, out nuint regionSize)
    {
        MEMORY_BASIC_INFORMATION mbi = Query(address);
        regionSize = mbi.RegionSize;
        return (uint)mbi.State;
    }

    /// <summary>Returns the <c>Type</c> of the region containing <paramref name="address"/> (<c>MEM_MAPPED</c> / <c>MEM_PRIVATE</c>).</summary>
    public static uint QueryType(ulong address) => (uint)Query(address).Type;

    private static MEMORY_BASIC_INFORMATION Query(ulong address)
    {
        MEMORY_BASIC_INFORMATION mbi;
        nuint n = PInvoke.VirtualQuery((void*)address, &mbi, (nuint)sizeof(MEMORY_BASIC_INFORMATION));
        if (n == 0)
        {
            throw new InvalidOperationException($"VirtualQuery failed with {Marshal.GetLastPInvokeError()}");
        }

        return mbi;
    }
}

/// <summary>Unique object names per test.</summary>
internal static class TestNames
{
    public static string Unique() => $"photone-test-{Environment.ProcessId}-{Guid.NewGuid():N}";

    public static string UniqueSection() => "Local\\photone." + Unique();
}
